#Requires -Version 5.1
<#
.SYNOPSIS
    Register Entra ID applications for ERP AI (FREE — no Azure subscription required).

.DESCRIPTION
    Creates two app registrations:
      1. ERP AI Delay Risk API  — exposes "predict" scope + EXEC/OPS/ANALYST app roles
      2. ERP AI Delay Risk Dashboard — delegated access to API scope

    Outputs config/entra/generated.env for use in Container Apps and local dev.
    Run: az login (works with free Microsoft Entra / M365 developer tenant)

.PARAMETER TenantId
    Optional tenant override. Defaults to current az account tenant.
#>
param(
    [string]$TenantId = ""
)

$ErrorActionPreference = "Stop"
$ProjectRoot = Resolve-Path (Join-Path $PSScriptRoot "..\..")
$OutputFile = Join-Path $ProjectRoot "config\entra\generated.env"

function New-AppRole([string]$DisplayName, [string]$Value, [string]$Description) {
    return @{
        allowedMemberTypes = @("User")
        description        = $Description
        displayName        = $DisplayName
        id                 = [guid]::NewGuid().ToString()
        isEnabled          = $true
        value              = $Value
    }
}

Write-Host "==> Checking Azure CLI / Entra access" -ForegroundColor Cyan
if (-not (Get-Command az -ErrorAction SilentlyContinue)) {
    Write-Host "Azure CLI (az) not found." -ForegroundColor Red
    Write-Host "Install: winget install Microsoft.AzureCLI"
    Write-Host "Or use manual setup: docs/entra-portal-setup.md"
    exit 1
}
$account = az account show | ConvertFrom-Json
if ($LASTEXITCODE -ne 0) {
    Write-Host "Not logged in. Run: az login" -ForegroundColor Red
    exit 1
}
if (-not $TenantId) { $TenantId = $account.tenantId }
Write-Host "Tenant: $TenantId"

Write-Host "==> Creating API app registration" -ForegroundColor Cyan
$predictScopeId = [guid]::NewGuid().ToString()
$apiApp = az ad app create `
    --display-name "ERP AI Delay Risk API" `
    --sign-in-audience "AzureADMyOrg" `
    --identifier-uris "api://erp-ai-delay-risk-api" `
    --app-roles (ConvertTo-Json @(
        (New-AppRole "EXEC" "EXEC" "Executive dashboard access"),
        (New-AppRole "OPS" "OPS" "Operations scoring workflows"),
        (New-AppRole "ANALYST" "ANALYST" "Read-only monitoring access")
    ) -Compress) `
    | ConvertFrom-Json

$apiClientId = $apiApp.appId
$apiObjectId = $apiApp.id

# Update identifier URI with actual client ID (Entra best practice)
az ad app update --id $apiObjectId --identifier-uris "api://$apiClientId" | Out-Null

# Expose API scope
$apiBody = @{
    api = @{
        oauth2PermissionScopes = @(
            @{
                adminConsentDescription = "Score ERP orders for shipment delay risk"
                adminConsentDisplayName = "Predict delay risk"
                id                      = $predictScopeId
                isEnabled               = $true
                type                    = "User"
                userConsentDescription  = "Score orders for delay risk"
                value                   = "predict"
            }
        )
    }
} | ConvertTo-Json -Depth 6 -Compress

az rest --method PATCH `
    --uri "https://graph.microsoft.com/v1.0/applications/$apiObjectId" `
    --headers "Content-Type=application/json" `
    --body $apiBody | Out-Null

Write-Host "API Client ID: $apiClientId" -ForegroundColor Green

Write-Host "==> Creating Dashboard app registration" -ForegroundColor Cyan
$dashApp = az ad app create `
    --display-name "ERP AI Delay Risk Dashboard" `
    --sign-in-audience "AzureADMyOrg" `
    --public-client-redirect-uris "https://login.microsoftonline.com/common/oauth2/nativeclient" "http://localhost:8501" `
    | ConvertFrom-Json

$dashClientId = $dashApp.appId
$dashObjectId = $dashApp.id

# Grant dashboard delegated permission to API predict scope
$dashPatch = @{
    requiredResourceAccess = @(
        @{
            resourceAppId  = $apiClientId
            resourceAccess = @(
                @{
                    id   = $predictScopeId
                    type = "Scope"
                }
            )
        }
    )
} | ConvertTo-Json -Depth 6 -Compress

az rest --method PATCH `
    --uri "https://graph.microsoft.com/v1.0/applications/$dashObjectId" `
    --headers "Content-Type=application/json" `
    --body $dashPatch | Out-Null

Write-Host "Dashboard Client ID: $dashClientId" -ForegroundColor Green

Write-Host "==> Writing $OutputFile" -ForegroundColor Cyan
$envContent = @"
# Generated by scripts/entra/register-apps.ps1 — $(Get-Date -Format o)
# Entra app registrations are FREE. Enable auth when ready.

ENTRA_TENANT_ID=$TenantId
ENTRA_API_CLIENT_ID=$apiClientId
ENTRA_API_AUDIENCE=api://$apiClientId
ENTRA_DASHBOARD_CLIENT_ID=$dashClientId
ENTRA_API_SCOPE=api://$apiClientId/predict

# Set to true when ready to enforce JWT validation
ENTRA_AUTH_ENABLED=false

# Dashboard auth mode: env | entra | dual
AUTH_MODE=env
"@

Set-Content -Path $OutputFile -Value $envContent -Encoding UTF8

Write-Host ""
Write-Host "Entra registration complete." -ForegroundColor Green
Write-Host "Next steps:"
Write-Host "  1. Assign users to EXEC/OPS/ANALYST app roles on the API app (Entra portal)"
Write-Host "  2. Grant admin consent for dashboard -> API predict scope"
Write-Host "  3. Test locally: AUTH_MODE=entra + source config/entra/generated.env"
Write-Host "  4. When APIM is active: uncomment validate-jwt in config/apim/policies/api-inbound-policy.xml"
